### ISSUE TITLE
More intuitive chain input

### ISSUE THREAD

**Issue by olgavrou** [VowpalWabbit/rl_chain#3]
examples:
- `chain.run(prefix = rl_chain.Embed(['action1', 'action2']))` 
- `chain.run(this_general_variable = "some other text")` {this_general_variable} to be used, for example, by user in prompt but ignored by VW in e.g. slates
- `chain.run(selected = rl_chain.ToSelectFrom(rl_chain.Embed(['action1', 'action2']), based_on = rl_chain.BasedOn("Tom"), a_prompt_value = "Another Tom")))`

**Comment by ataymano** [comment]
alternative approach:
- `chain.based_on({"A": "Tom"}).(selected = rl_chain.ToSelectFrom(rl_chain.Embed(['action1', 'action2']), a_prompt_value = "Tom")))` . 

Pros: context and actions are naturally separated so one more helper can be omitted (either Ignore or SelectFrom)
Cons: requires nontrivial messing with the state

**Comment by olgavrou** [comment]
next steps

- support `{"user":["Tom", "Age"]}`
- try to use `base.embed()` in slates
- continue with `ToSelect` and `Ignore`

**Comment by olgavrou** [comment]
basic idea is done, we can open other issues for more improvements
